import type { Table, TableOptions, TableState } from '@tanstack/react-table';

/**
 * Extended sort state with specific additions for the data table.
 */
export type ExtendedColumnSort = {
  id: string;
  desc: boolean;
};

/**
 * Props accepted by the `useDataTable` hook.
 *
 * This hook extends `TableOptions` from `@tanstack/react-table` with several
 * additional properties to simplify table configuration (such as pagination, sorting, and filtering)
 * for both internal (uncontrolled) and external (controlled) state management.
 *
 * @template TData The data type of the table row.
 */
export interface UseDataTableProps<TData>
  extends Omit<
    TableOptions<TData>,
    | 'state'
    | 'pageCount'
    | 'getCoreRowModel'
    | 'manualFiltering'
    | 'manualPagination'
    | 'manualSorting'
  > {
  /**
   * The total number of pages from the data source (for server-side pagination).
   * This value is required when using server-side pagination.
   * Defaults to -1 if unknown.
   */
  pageCount: number;

  /**
   * Initial state configuration for the table.
   * Useful for defining the default sorting, filters, or column visibility when the table first renders.
   */
  initialState?: Omit<Partial<TableState>, 'sorting'> & {
    /**
     * The initial sorting condition for the columns.
     */
    sorting?: ExtendedColumnSort[];
  };

  /**
   * The delay time in milliseconds (ms) for the debounce process when the user types in the filter column.
   * Useful to prevent excessive API calls to the server on every input stroke (throttling requests).
   *
   * @default 300
   */
  debounceMs?: number;

  /**
   * Flag to enable advanced filtering.
   * If set to `true`, the standard column filters will be disabled internally
   * to prioritize more complex external queries/filters.
   *
   * @default false
   */
  enableAdvancedFilter?: boolean;

  /**
   * The currently active page (controlled state).
   * If this property is provided, the table will use this value as the source of truth
   * and ignore its own internal page state.
   */
  page?: number;

  /**
   * The limit of data rows displayed per page (controlled state).
   * If this property is provided, the table will use this value as the source of truth.
   */
  perPage?: number;

  /**
   * Callback function that is automatically triggered whenever the active page changes.
   * Highly useful when utilizing server-side pagination to trigger data refetching.
   *
   * @param page The newly selected page (1-based index).
   */
  onPageChange?: (page: number) => void;

  /**
   * Callback function that is automatically triggered whenever the row limit per page changes.
   * Useful for adjusting the query limit to the server.
   *
   * @param perPage The new number of rows per page (limit).
   */
  onPerPageChange?: (perPage: number) => void;
}

/**
 * Return value of the `useDataTable` hook.
 *
 * Returns an object containing the table instance from `@tanstack/react-table`
 * along with supporting state variables to be used in the table UI.
 *
 * @template TData The data type of the table row.
 */
export interface UseDataTableReturn<TData> {
  /**
   * The main Table instance object generated by `@tanstack/react-table`.
   * This instance contains all the methods and states for rendering data, columns, pagination, and other table interactions.
   *
   * @see https://tanstack.com/table/v8/docs/api/core/table
   */
  table: Table<TData>;
}
