import type { DateRange, DayPickerProps } from 'react-day-picker';
import type { Control, FieldPath, FieldValues } from 'react-hook-form';

/**
 * Base props shared by all `FormDatePicker` variants.
 */
type BaseProps<TFieldValues extends FieldValues> = {
  /**
   * React Hook Form `control` object returned from `useForm`.
   * Used to connect the date picker with form state management.
   */
  control: Control<TFieldValues>;

  /**
   * Dot-notation path to the field inside the form schema.
   * Fully type-safe — TypeScript will error if the field path does not exist.
   */
  name: FieldPath<TFieldValues>;

  /**
   * Optional label rendered above or beside the date picker trigger.
   */
  label?: string;

  /**
   * Layout orientation of the form item.
   *
   * - `vertical`: Label is stacked above the field (default).
   * - `horizontal`: Label is rendered side-by-side with the field.
   *
   * @default "vertical"
   */
  layout?: 'vertical' | 'horizontal';

  /**
   * Formatter function used to convert the selected date value
   * into a human-readable label shown inside the trigger element.
   */
  formatLabel: (value?: Date | DateRange) => string;

  /**
   * Additional class names applied to the outermost `FormItem` wrapper.
   */
  className?: string;

  /**
   * Additional class names applied to the label element.
   * Useful for width adjustment in horizontal layouts.
   */
  labelClassName?: string;

  /**
   * Custom renderer for the trigger element.
   *
   * Receives:
   * - `label`: Formatted label returned from `formatLabel`
   * - `value`: Current selected date value
   *
   * Must return a single React element.
   */
  render: (params: {
    /**
     * Formatted label generated by `formatLabel`.
     */
    label: string;

    /**
     * Current selected value from the calendar.
     */
    value?: Date | DateRange;
  }) => React.ReactElement<{
    children?: React.ReactNode;
    className?: string;
  }>;
};

/**
 * Supported `react-day-picker` calendar modes.
 *
 * - `PropsSingle` → Single date selection
 * - `PropsRange` → Date range selection
 * - `PropsMulti` → Multiple date selection
 */
type CalendarProps = DayPickerProps;

/**
 * Props for the internal date picker configuration.
 */
export type DatePickerProps<TFieldValues extends FieldValues> = BaseProps<TFieldValues> & {
  /**
   * Props forwarded directly to the underlying `Calendar` component.
   *
   * Supports all `react-day-picker` modes:
   * - single
   * - range
   * - multiple
   */
  datePickerProps: CalendarProps;
};

/**
 * Props accepted by the `FormDatePicker` component.
 */
export type FormDatePicker<TFieldValues extends FieldValues> = DatePickerProps<TFieldValues>;
