name: Release & Deploy

on:
  push:
    tags:
      - "v*"

concurrency:
  group: production-Deploy
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    outputs:
      version: ${{ steps.version.outputs.version }}


    steps:
      - name: Debug Deploy
        run: |
          echo "VERSION=${{ needs.docker-build.outputs.version }}"
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Get Version from tag
        id: version
        run: | 
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GHCR 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: | 
            ghcr.io/${{ github.repository }}/docs:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository }}/docs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            VERSION="${{ needs.docker-build.outputs.version }}"

            IMAGE=ghcr.io/${{ github.repository }}/docs:${{ needs.docker-build.outputs.version }}

            echo "Deploying $IMAGE"

            docker login ghcr.io \
              -u ${{ github.actor }} \
              -p ${{ secrets.TOKEN_GITHUB }}

            docker pull $IMAGE

            docker stop komdes-docs || true
            docker rm komdes-docs || true

            docker run -d \
              --name komdes-docs \
              --restart unless-stopped \
              -p 3000:3000 \
              $IMAGE


      
